### PR TITLE
Fix for older browsers

### PR DESCRIPTION
**Pull request by a-mabe**
- Site now works on older versions of Chrome and Firefox
- Also added another fix for the histogram page occasionally not fully loading

### CODE REVIEW

**Comment by ibnesayeed** [comment]
How critical it is to support older browsers? Why are you getting rid of a more standard `placeholder` attribute in favor of a rather hacky approach of using values and clearing it then repopulating on focus and blur?

By the way if I can understand it correctly, you current logic will wipe the value off if someone intentionally filled the default value and the blur the focus out of the field.

**Comment by a-mabe** [comment]
It is to fix issue #52. If the user clicks the data field to type their own input, the field clears so that they don't have to erase it. If the user clicks out of the data field, the default value refills so they can still see the example input. This fix is working on current versions of Chrome and Firefox, as well as the versions mentioned in issue #52.

**Comment by ibnesayeed** [comment]
I have commented in #52 about it.

**Comment by ibnesayeed** [comment]
Let me know when you feel it is ready to be merged.

**Comment by a-mabe** [comment]
It is ready, it's working on old and new versions of browsers. Thank you!

**Comment by ibnesayeed** [comment]
I am merging this, but in a separate PR you might want to remove alert dialogue and add inline validation for a better user experience.

**Pull request merged**
