### PR TITLE
URI stamp for multiple URI input.

### PR DESCRIPTION
**Pull request by a-mabe**
- When a user enters more than one URI separated by a comma, the GIF has the option of watermarking each image with its associated URI.

- The user may also choose to watermark the images with the URI and timestamp together.

- Additionally, the image grid displays the URI underneath the datetime so that the user knows which of their input URIs that specific memento came from.

### CODE REVIEW

**Comment by ibnesayeed** [comment]
Comma is a valid character in URIs, how can you separate them with commas?

**Comment by a-mabe** [comment]
Separating different input parameters with a comma is how Dr. Weigle requested the multiple URI input be implemented based off of a feature request. Example: cs.odu.edu, odu.edu/compsci. This feature allows the user to combine timemaps for a website that had changed its domain name into a single timemap.

**Comment by ibnesayeed** [comment]
You might want to discuss this with @weiglemc, because if a URI contains comma in it, you will end up splitting it at a wrong place. You have some options here:

* Use a multi-line textarea field as input instead of a single line text input field and ask users to enter each URL in a separate line
* Use multiple fields for URIs and allow users to dynamically add as many fields as they want. In that case, the `name` attribute does not have to be `uri1`, `uri2`, `uri3` and so on, instead you can use `uri[]` as the name and it will handle repeated values as a list

**Comment by weiglemc** [comment]
This feature is already addressing an uncommon case, so I don't want to add complexity to the UI to support it.  

Couple options:
* ", " as a delimiter and enforce the space after the comma
* allow URIs that contain commas to be surrounded by quotation marks
* do URI verification on the resulting URIs that are split by commas so that if the 2nd one isn't valid, then it is assumed that the comma was part of the first URI and the original (unsplit) URI would be used

We won't support using multiple URIs that contain commas -- took much work for a corner case.

**Comment by ibnesayeed** [comment]
> ", " as a delimiter and enforce the space after the comma

A comma suffixed to a URI will be considered to be part of the leading URI by a URI parser and space alone is also not too safe because it will be URL-encoded as `%20` which could be difficult to isolate from the spaces in query parameters.

> allow URIs that contain commas to be surrounded by quotation marks

This could work, but will require more inline documentation for users.

I still feel that using a textarea can be the simplest approach without too much UI or API change. The server can easily split values on `%0a` (URL-encoding of new line character). This use case is not uncommon, for example many shipping tracking sites would allow entering multiple tracking numbers in separate lines or IP to location services allow entering multiple IP addresses in text area to be submitted at once.

**Comment by weiglemc** [comment]
We can add the textarea change as a feature request for later, but I'd rather leave it as it is for now and roll out what we have.

**Comment by ibnesayeed** [comment]
In that case, if this is tested and ready, I can merge it and push it to the pipeline to be deployed once the Docker image is built.

**Pull request merged**
